version: "3.7"

services:

  gameserver:
    build:
      context: .
      dockerfile: ./Dockerfile.GameServer
    environment:
      NODE_ENV: "development"
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - redis
      - arangodb

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile.WebServer
    environment:
      NODE_ENV: "development"
      PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - redis
      - arangodb

  redis:
    image: redis

  arangodb:
    image: arangodb
    environment:
      ARANGO_NO_AUTH: 1