version: "3.7"

services:

  gameserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: "node /app/out/app/GameServer.js"
    environment:
      NODE_ENV: "development"
      PORT: 3000
      TIMEOUTS_CONFIG_CACHE: 6h
    ports:
      - 3000:3000
    depends_on:
      - redis
      - arangodb

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: "node /app/out/app/WebServer.js"
    environment:
      NODE_ENV: "development"
      PORT: 3001
      TIMEOUTS_CONFIG_CACHE: 6h
    ports:
      - 3001:3001
    depends_on:
      - redis
      - arangodb

  redis:
    image: redis

  arangodb:
    image: arangodb
    environment:
      ARANGO_NO_AUTH: 1